---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://stefanprodan.github.io/podinfo
      chart: podinfo
      targetRevision: 6.7.0
      helm:
        valueFiles:
          - values.yaml
  destination:
    name: in-cluster
    namespace: podinfo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
