apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/imtpot/argocd-demo.git
        revision: appsets
        files:
          - path: argocd/apps/**/values.yaml
  template:
    metadata:
      name: "{{index .path.segments 1}}-{{index .path.segments 3}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/imtpot/argocd-demo.git
        targetRevision: appsets
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{index .path.segments 1}}-{{index .path.segments 3}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
