---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd
      targetRevision: 7.3.7
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
