apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - path: root-patch.yaml
    target:
      kind: Application
      name: root
  - path: appset-template-patch.yaml
    target:
      kind: ApplicationSet
      name: appset-template
