name: argocd
namespace: argocd
source:
  repoURL: https://argoproj.github.io/argo-helm
  targetRevision: 7.3.8
  chart: argo-cd

values:
  # Add lovely-vault-plugin to the repo-server pod
  repoServer:
    extraContainers:
      - name: lovely-plugin
        image: ghcr.io/crumbhole/lovely-vault-plugin:1.0.3
        envFrom:
          - secretRef:
              name: vault-credentials
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: lovely-tmp
    volumes:
      - emptyDir: {}
        name: lovely-tmp
    envFrom:
      - secretRef:
          name: vault-credentials
  extraObjects:
    - kind: Secret
      apiVersion: v1
      metadata:
        name: vault-credentials
      type: Opaque
      stringData:
        AVP_TYPE: vault
        AVP_AUTH_TYPE: k8s
        AVP_K8S_ROLE: argocd-repo-server
        VAULT_ADDR: http://vault.vault:8200
  configs:
    exec.enabled: true
    cmp:
      create: true
      plugins:
        lovely-vault-plugin:
          init:
            command: [sh, -c]
            args: ["helm dependency build"]
          generate:
            command: ["sh", "-c"]
            args:
              [
                "helm template $ARGOCD_APP_NAME . --include-crds | argocd-vault-plugin generate -",
              ]
