repositories:
  - name: podinfo
    url: https://stefanprodan.github.io/podinfo

releases:
  - name: podinfo-2
    namespace: podinfo-2
    chart: podinfo/podinfo
    values:
      - replicaCount: 2
      - values.yaml
