---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: https://github.com/imtpot/argocd-demo.git
    targetRevision: HEAD
    path: argocd/applications/base/
  destination:
    name: in-cluster
    namespace: podinfo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
# # apiVersion: argoproj.io/v1alpha1
# # kind: Application
# # metadata:
# #   name: podinfo
# #   namespace: argocd
# # spec:
# #   project: applications
# #   sources:
# #     - repoURL: https://stefanprodan.github.io/podinfo
# #       chart: podinfo
# #       #targetRevision: 6.7.0
# #   destination:
# #     name: in-cluster
# #     namespace: podinfo
# #   syncPolicy:
# #     syncOptions:
# #       - CreateNamespace=true
# #     automated:
# #       selfHeal: true
