---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: applications
  sources:
    - repoURL: https://stefanprodan.github.io/podinfo
      chart: podinfo
      targetRevision: 7.3.7
  destination:
    name: in-cluster
    namespace: podinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
