- op: replace
  path: /spec/generators/0/git/files/0/path
  value: "argocd/applications/*/production/app-config.yaml"
- op: replace
  path: /spec/generators/1/git/files/0/path
  value: "argocd/infrastructure/*/production/app-config.yaml"
